# Generated by Django 5.2.7 on 2025-10-26 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MAT', 'Matematik'), ('FIZ', 'Fizik'), ('KIM', 'Kimya'), ('BIO', 'Biyoloji'), ('GEO', 'Geometri')], max_length=3)),
                ('difficulty', models.CharField(choices=[('E', 'Kolay'), ('M', 'Orta'), ('H', 'Zor')], max_length=1)),
                ('stem', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('answer', models.CharField(max_length=1)),
                ('rubric', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='ai', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MAT', 'Matematik'), ('FIZ', 'Fizik'), ('KIM', 'Kimya'), ('BIO', 'Biyoloji'), ('GEO', 'Geometri')], max_length=3)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1)),
                ('correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.topic'),
        ),
    ]
