# Generated by Django 5.2.7 on 2025-11-10 11:29

import django.db.models.deletion
from django.db import migrations, models

def convert_difficulty_to_numeric(apps, schema_editor):
    """Convert old difficulty text values to new numeric values"""
    Question = apps.get_model('quiz', 'Question')

    # Mapping of old values to new numeric values
    difficulty_mapping = {
        'E': 2,  # Kolay -> 2
        'M': 3,  # Orta -> 3
        'H': 4,  # Zor -> 4
    }

    # Update all questions with old difficulty values
    for old_value, new_value in difficulty_mapping.items():
        Question.objects.filter(difficulty=old_value).update(difficulty=new_value)

def reverse_convert_difficulty_to_text(apps, schema_editor):
    """Reverse conversion: numeric values back to text"""
    Question = apps.get_model('quiz', 'Question')

    # Mapping of new numeric values back to old text values
    reverse_mapping = {
        2: 'E',  # 2 -> Kolay
        3: 'M',  # 3 -> Orta
        4: 'H',  # 4 -> Zor
    }

    # Update all questions with numeric difficulty values
    for new_value, old_value in reverse_mapping.items():
        Question.objects.filter(difficulty=new_value).update(difficulty=old_value)

def handle_null_topics(apps, schema_editor):
    """Handle questions with null topic values"""
    Question = apps.get_model('quiz', 'Question')
    Topic = apps.get_model('quiz', 'Topic')
    Subject = apps.get_model('quiz', 'Subject')

    # Use an existing subject instead of creating a new one to avoid code length issues
    try:
        # Try to find an existing subject first
        default_subject = Subject.objects.first()
        if not default_subject:
            # If no subjects exist, create one with a short code
            default_subject, _ = Subject.objects.get_or_create(
                code="MAT",  # Use existing code format
                defaults={"name": "Matematik"}
            )
    except Exception:
        # If there's any error, create a simple default
        default_subject, _ = Subject.objects.get_or_create(
            code="MAT",
            defaults={"name": "Matematik"}
        )

    # Create or get a default topic
    default_topic, _ = Topic.objects.get_or_create(
        name="Genel",
        defaults={
            "subject": default_subject,
            "phase": "TYT"
        }
    )

    # Update all questions with null topics to use the default topic
    Question.objects.filter(topic__isnull=True).update(topic=default_topic)

def reverse_handle_null_topics(apps, schema_editor):
    """Reverse: set topic back to null for default topic questions"""
    Question = apps.get_model('quiz', 'Question')
    Topic = apps.get_model('quiz', 'Topic')

    try:
        default_topic = Topic.objects.get(name="Genel")
        Question.objects.filter(topic=default_topic).update(topic=None)
    except Topic.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='stem',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='question',
            name='source',
        ),
        migrations.AddField(
            model_name='question',
            name='cognitive',
            field=models.CharField(default='Kavrama', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='phase',
            field=models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT'), ('BOTH', 'Her İkisi')], default='TYT', max_length=4),
            preserve_default=False,
        ),
        # Handle data conversion after all schema changes
        migrations.RunPython(
            convert_difficulty_to_numeric,
            reverse_convert_difficulty_to_text,
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        # Make topic nullable to avoid issues during migration
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Misconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_label', models.CharField(max_length=1)),
                ('description', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('selected_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('measures_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('exam', models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT')], max_length=3)),
                ('question_text', models.TextField()),
                ('choices', models.JSONField(default=dict)),
                ('correct_answer', models.CharField(max_length=1)),
                ('cognitive_level', models.CharField(max_length=50)),
                ('difficulty', models.PositiveSmallIntegerField(default=3)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='quiz.subject'),
        ),
        migrations.CreateModel(
            name='Subskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subskills', to='quiz.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=200)),
                ('weight', models.FloatField(default=1.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='quiz.question')),
                ('subskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subskill')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subskills',
            field=models.ManyToManyField(blank=True, to='quiz.subskill'),
        ),
    ]
