# Generated by Django 5.2.7 on 2025-11-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('document_type', models.CharField(choices=[('CURRICULUM', 'Müfredat/Konu Anlatımı'), ('PAST_EXAM', 'Geçmiş Sınav Soruları')], max_length=10)),
                ('exam_type', models.CharField(blank=True, choices=[('TYT', 'TYT'), ('AYT', 'AYT'), ('BOTH', 'Her İkisi')], max_length=4)),
                ('year', models.IntegerField(blank=True, help_text="Sadece geçmiş sınav PDF'leri için", null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Embeding işlemi yapıldı mı?')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('PROCESSING', 'İşleniyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Hata')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='quiz.pdfdocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['document_type', 'exam_type'], name='quiz_pdfdoc_documen_45fe8f_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['year'], name='quiz_pdfdoc_year_d68514_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['is_processed'], name='quiz_pdfdoc_is_proc_73d9f5_idx'),
        ),
    ]
