# Generated by Django 5.2.8 on 2025-11-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_pdfdocument_pdfprocessinglog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfprocessinglog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfprocessinglog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pdfprocessinglog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfprocessinglog',
            name='status',
            field=models.CharField(choices=[('QUEUED', "Queue'de Bekliyor"), ('PROCESSING', 'İşleniyor'), ('SUCCESS', 'Başarılı'), ('ERROR', 'Hata'), ('CLEANUP', 'Temizlik')], max_length=10),
        ),
    ]
