# Generated by Django 5.2.7 on 2025-11-12 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_pdfprocessinglog_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('exam_type', models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT')], max_length=20)),
                ('branch', models.CharField(choices=[('SAY', 'Sayısal'), ('EA', 'Eşit Ağırlık'), ('SOZ', 'Sözel')], max_length=20)),
                ('question_count', models.IntegerField(default=12)),
                ('duration_minutes', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('merged', 'Birleştirildi'), ('expired', 'Süresi Doldu')], default='active', max_length=20)),
                ('temp_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uuid', models.UUIDField(blank=True, help_text="TempExamResult uuid'si", null=True)),
                ('exam_type', models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT')], max_length=20)),
                ('branch', models.CharField(choices=[('SAY', 'Sayısal'), ('EA', 'Eşit Ağırlık'), ('SOZ', 'Sözel')], max_length=20)),
                ('total_questions', models.IntegerField()),
                ('correct_count', models.IntegerField()),
                ('wrong_count', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('subject_breakdown', models.JSONField(default=dict)),
                ('is_quick_test', models.BooleanField(default=False, help_text='Hızlı test mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TempExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_questions', models.IntegerField()),
                ('correct_count', models.IntegerField()),
                ('wrong_count', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('subject_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='quiz.tempexamsession')),
            ],
        ),
        migrations.CreateModel(
            name='TempExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.tempexamsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
