# Generated by Django
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_tempexamsession_examresult_tempexamresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('browser_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_test_count', models.IntegerField(default=0)),
                ('weekly_test_count', models.IntegerField(default=0)),
                ('total_test_count', models.IntegerField(default=0)),
                ('last_test_date', models.DateTimeField(null=True, blank=True)),
                ('blocked_until', models.DateTimeField(null=True, blank=True)),
                ('block_reason', models.CharField(max_length=100, blank=True)),
            ],
            options={
                'verbose_name': 'Anonymous User',
                'verbose_name_plural': 'Anonymous Users',
                'indexes': [
                    models.Index(fields=['browser_id'], name='idx_browser_id'),
                    models.Index(fields=['ip_address'], name='idx_ip_address'),
                    models.Index(fields=['last_seen'], name='idx_last_seen'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AnonymousStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anonymous_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='quiz.anonymoususer')),
                ('exam_type', models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT')], max_length=20)),
                ('branch', models.CharField(choices=[('SAY', 'Sayısal'), ('EA', 'Eşit Ağırlık'), ('SOZ', 'Sözel')], max_length=20)),
                ('total_tests', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('best_score', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('last_test_date', models.DateTimeField(null=True, blank=True)),
                ('subject_mastery', models.JSONField(default=dict)),
                ('improvement_trend', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anonymous Statistics',
                'verbose_name_plural': 'Anonymous Statistics',
                'indexes': [
                    models.Index(fields=['anonymous_user', 'exam_type', 'branch'], name='idx_user_exam_branch'),
                    models.Index(fields=['last_test_date'], name='idx_last_test_date'),
                ],
                'unique_together': {('anonymous_user', 'exam_type', 'branch')},
            },
        ),
        migrations.AddField(
            model_name='tempexamsession',
            name='anonymous_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='quiz.anonymoususer'),
        ),
        migrations.AddField(
            model_name='tempexamresult',
            name='anonymous_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='quiz.anonymoususer'),
        ),
    ]