# Generated by Django 5.0.7 on 2025-11-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_add_anonymous_user_to_temp_exam_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempexamresult',
            name='anonymous_user',
        ),
    ]
