# Generated by Django 5.0.7 on 2025-11-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_tempexamresult_anonymous_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Hangi sorunun kopyası olduğu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='embedding_vector',
            field=models.JSONField(blank=True, help_text='Vektör gösterimi (gelecek kullanım için)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Kopya soru olarak işaretlendi mi?'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_similarity_check',
            field=models.DateTimeField(blank=True, help_text='Son benzerlik kontrol tarihi', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='En yüksek benzerlik skoru (0-1 arası)', null=True),
        ),
    ]
