# Generated by Django 5.0.7 on 2025-11-20 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_duplicate_of_question_embedding_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('average_time_seconds', models.FloatField(default=0)),
                ('difficulty_distribution', models.JSONField(default=dict)),
                ('topic_performance', models.JSONField(default=dict)),
                ('improvement_score', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user_identifier', 'date'], name='quiz_userpe_user_id_afb651_idx'), models.Index(fields=['subject', 'date'], name='quiz_userpe_subject_e5aae8_idx')],
                'unique_together': {('user_identifier', 'subject', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=255)),
                ('answered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answer_given', models.CharField(blank=True, max_length=1, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.tempexamsession')),
            ],
            options={
                'ordering': ['-answered_at'],
                'indexes': [models.Index(fields=['user_identifier', 'answered_at'], name='quiz_userqu_user_id_c6f0f4_idx'), models.Index(fields=['user_identifier', 'question'], name='quiz_userqu_user_id_60f3d7_idx'), models.Index(fields=['session', 'answered_at'], name='quiz_userqu_session_f9e203_idx')],
                'unique_together': {('user_identifier', 'question')},
            },
        ),
    ]
